### ISSUE TITLE
Week of 07/14/16

### ISSUE THREAD

**Issue by bigfatnoob** [dr-bigfatnoob/RaiseReports#1]
### Citemap
- [x] Publication pattern for top 1% authors [#4](https://github.com/ai-se/citemap/issues/4#issuecomment-231613385)
- [x] Paper [here](https://github.com/ai-se/citemap/blob/master/citemap.pdf)
### Baseline
- [x] 10 way cross val results for [Mean Standard Accuracy](https://github.com/ai-se/baseline/issues/10)
- [x] 10 way cross val results for [Mean Relative Error](https://github.com/ai-se/baseline/issues/11)
- [x] 10 way cross val results for [RE*](https://github.com/ai-se/baseline/issues/12) (Proposed by Whigham etal)
- [x] [Consolidated](https://github.com/ai-se/baseline/issues/13)
- [ ] Need to discuss what do suggest as better baseline modified ABE0 or PALM.
### LOC Error 2
- [ ] [Issues](https://github.com/ai-se/LOC_error2/issues)
- [ ] Need to proof read paper.
### Dialog Operators
- [ ]  Numerous small [tasks](https://github.com/ai-se/eebm/issues).
